name: Verify
on: [push, pull_request]

jobs:
  verify:
    uses: BaylorRae/setup-rails/.github/workflows/verify.yml@main
    # uncomment to enable options:
    #
    # with:
    #   brakeman: true
    #   bundler-audit: true
    #   rspec: true
    #   rubocop: true
    #   standard: true
